name: Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Durgesh-Nikam
          outputs: |
            github-snake.svg
            github-snake-dark.svg

      - name: Push snake
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout --orphan output
          git rm -rf .
          mv github-snake*.svg .
          git add .
          git commit -m "Generate snake"
          git push -f origin output
