name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Durgesh-Nikam
          outputs: |
            assets/snake.svg?color_snake=00ff00&color_dots=ebedf0,9be9a8,40c463,30a14e
            assets/snake-dark.svg?color_snake=00ff00&color_dots=161b22,0e4429,006d32,26a641


      - name: Commit snake
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/
          git commit -m "Update snake animation" || echo "No changes"
          git push
